### ISSUE TITLE
undefined is not an object (evaluating 'SMXCrashlytics.crash') - this crash is on iOS

### ISSUE THREAD

**Issue by s2zaman** [corymsmith/react-native-fabric#102]
![image](https://cloud.githubusercontent.com/assets/5410255/22770558/38bde864-eeb3-11e6-871e-027ec914c24f.png)

Getting this issue while have followed the steps mentioned in official docs.

Have anyone encountered this issue before ?

**Comment by jnrepo** [comment]
@s2zaman 

yes having this issue here

react-native: 0.38.1
react-native-fabric: 0.3.2
iOS 10

**Comment by jnrepo** [comment]
@s2zaman 

This is what I did to get it to work

1. Followed the steps with Fabric.io and setup Crashlytics through the Fabric app.
2. Install with `npm i react-native-fabric@^0.3.2` (0.3.2 since my project uses react-native 0.38.1, if your react-native version is >0.40 use 0.4.0)
3. `react-native link react-native-fabric`
4. Then I dragged the library here (first screenshot) into (second screenshot)
![screen shot 2017-02-12 at 9 09 31 pm](https://cloud.githubusercontent.com/assets/5111058/22871692/2474bbfa-f168-11e6-8fb7-e3252132ff47.png)
![screen shot 2017-02-12 at 9 10 02 pm](https://cloud.githubusercontent.com/assets/5111058/22871701/3bce04f0-f168-11e6-85c6-b06c156e5cb8.png)

And that seemed to solved the error you get above. Hope this helps!

**Comment by s2zaman** [comment]
@jnrepo thanks for that idea.
I had missed the part **Link Binary With Libraries**

Just solved my issue, with your explained solution. 👍 🥇

**Comment by daemir** [comment]
@jnrepo I'm still getting this issue.. even with your solution. And everyone now and then when I follow your instructions again I'm getting a `Crashlytics/Crashlytics.h file not found error` in Xcode.

Any suggestions?

**Comment by iclems** [comment]
Also experiencing ```Crashlytics/Crashlytics.h file not found error```

**Comment by jnrepo** [comment]
@daemir @iclems what module versions are you all using?

**Comment by ghe0106** [comment]
above solution worked for me thanks - only needed to link really

**Comment by shreyaspadhye3011** [comment]
`Android` - Faced same issue. Turns out I missed out on linking the library as it is not specifically mentioned anywhere on the npm page.

Executed react-native link and that solved the problem for me. Hope this helps somebody.

**Comment by jdelafon** [comment]
Why is this closed? I've been on this issue for 5 hours now, and still `undefined is not an object (evaluating 'SMXCrashlytics.crash')`. I reinstalled XCode, cloned my repo that was working, cleared every cache I could.

**Comment by shreyaspadhye3011** [comment]
Android - did you run react-native link? 

IOS - jnrepo this comment worked for me: https://github.com/corymsmith/react-native-fabric/issues/102#issuecomment-279296313

Also, in ios if you do not find the SMXCrashlytics.xcodeproj in right pane as mentioned in the comment, import it from node_modules/react-native-fabric/ios/SMXCrashlytics.xcodeproj

**Comment by jdelafon** [comment]
iOS: Follow installation steps from Fabric desktop app to add Crashlytics, then `react-native link` solved it for us.

**Comment by FaiChou** [comment]
In iOS I figure it out:

1. Find the file in `YOURPROJECT_ROOT/node_modules/react-native-fabric/ios/SMXCrashlytics.xcodeproj` in Finder

![image](https://user-images.githubusercontent.com/18500846/38921243-d6b0432c-4327-11e8-8a79-9ddf872e2781.png)


2. Drag the SMXCrashlytics.xcodeproj to Libraries folder in Xcode navigator.

![image](https://user-images.githubusercontent.com/18500846/38921332-15d7b86e-4328-11e8-96b4-e7087e23b309.png)


3. Go `Xcode - Build Phases - Link Binary With Libraries`, Press `+` add button, then search `libSMXCrash` -> select `libSMXCrashlytics.a`

![image](https://user-images.githubusercontent.com/18500846/38921580-bc1b3610-4328-11e8-900f-36cee5bd69c4.png)


4. CMD+R run your app will be OK.

**Comment by bogdanbolchis** [comment]
This thread helped me because I had forgotten to add libSMXCrashlytics.a to the Link Binary With Libraries section of the target. 

For people running into `SMXCrashlytics.m:2:9: 'Crashlytics/Crashlytics.h' file not found`, my solution was to edit the SMXCrashlytics.xcodeproj's Framework Search Paths which were referencing an incorrect path for Crashlytics--it assumes your iOS project is sitting at `$(SRCROOT)/../../../ios`, whereas my project wasn't named ios. Here are the all the integration steps I did:

1. `react-native install react-native-fabric`
2. Main iOS project > Edit Scheme > Build > "+" to add the SMXCrashlytics target (above the main project's target)
3. Add libSMXCrashlytics.a to Link Binary With Libraries
4. Edit SMXCrashlytics.xcodeproj's Framework Search Paths to point to the right Crashlytics location
5. In the ReactNative app, do `import { Crashlytics } from 'react-native-fabric';` and call         `Crashlytics.crash();` to make sure it works.

**Comment by tmaly1980** [comment]
I had to do what @bogdanbolchis suggested, but SMXCrashlytics.xcodeproj needed to have React linked in the Header Search Paths:

```
$(SRCROOT)/../../../ios/Pods/Headers/Public/React
```

Otherwise, I'd get errors about SMXCrashlytics failing and React/RCTBridgeModule.h not being found.

**Comment by isaaclem** [comment]
@tmaly1980 : Do you mind to show a more detailed steps on how to fix the issue as my project is on Pod

<img width="519" alt="ss" src="https://user-images.githubusercontent.com/32945572/47138710-b96f6400-d2ec-11e8-879b-342982822fc8.png">
<img width="642" alt="screen shot 2018-10-18 at 3 44 00 pm" src="https://user-images.githubusercontent.com/32945572/47138728-c4c28f80-d2ec-11e8-8a66-704eddd1d97d.png">

I'm wondering if I should update "Framework Search Paths" or "Header Search Paths"? My "Header Search Paths" is currently empty
