### ISSUE TITLE
[IOS] 'Fabric/Fabric.h' file not found

### ISSUE THREAD

**Issue by jatarga** [corymsmith/react-native-fabric#164]
When I build, I'm getting this error:

`'Fabric/Fabric.h' file not found` in AppDelegate.m

Can anyone instruct me to how to install Fabric & Crashlytics? I'm having hard time to integrate it because I didn't use Xcode much.

What I've done:

* Downloaded and extracted Crashlytics & Fabric project to my project root folder
* `npm i --save react-native-fabric` && `react-native link react-native-fabric`
* Created a Run Script from Build Phase: `"${SRCROOT}/Crashlytics/Fabric.framework/run" API_KEY API_SECRET`

I'm not using Pods.

**Comment by c100k** [comment]
Have you added

```
#import <Fabric/Fabric.h>
#import <Crashlytics/Crashlytics.h>
```

on top of your `AppDelegate.m` ?

**Comment by lugrugzo** [comment]
Yes.

**Comment by rudyryk** [comment]
Try to install Fabric into your project with an app https://fabric.io/downloads/xcode

This is not `react-native-fabric` issue but rather XCode project configuration one, `react-native link` doesn't provide complete project configuration (and not supposed to do in this case).

**Comment by rudyryk** [comment]
> Downloaded and extracted Crashlytics & Fabric project to my project root folder

This is not enough, frameworks should be properly added to XCode project, so it could find libs and headers.

**Comment by rahamin1** [comment]
@sircEUNHO @rudyryk @jatarga @c100k If any of you can help, I will be grateful

I am struggling for the last 3 days with Crashlytics setup... Need help from somebody who did it...

I followed the instructions in https://fabric.io/kits/ios/crashlytics/install, as following:

1. Added the kit to podile, ran `pod install`
2. Added a run script build phase. The instructions say to add `"${PODS_ROOT}/Fabric/run"` and the long key. What did you specify for `${PODS_ROOT}`? An absolute path? A relative path? 
I searched for the `Fabric` folder. It is under `node_modules/react-native/React`, but there is no `run` script/file in this folder. Do you have such a file?
3. I am runing Xcode 10, and the instructions said to add an input file (to the run script) as well. I assume that this is the path to `podfile`, right? Did you use an absolute path? Relative?
4. Added the API key to info.plist. Seems clear.
5. Added `#import <Fabric/Fabric.h>` to AppDelegate.m (the instructions say to add it to `AppDelegate.swift`, but since I didn't find this file, I saw somewhere that the actual file is `AppDelegate.m`. I am getting, in the editor, the message `Fabric/Fabric.h not found`.

@rudyryk I tried to install Crashlytics from https://fabric.io/downloads/xcode. After download, I chose the project and a spinner was displayed. I expected it to stop, but it didn't. There was a message along this spinner saying 'run build'... Build still fails, obviously (since I have that error in AppDelegate.m).

@sircEUNHO  You write "Fix this, just add ${SRCROOT}/Crashlytics on your framework searchpath". Where exactly did you add it? 

As I wrote above any help will be appreciated. I am stuck :(

**Comment by magick93** [comment]
@corymsmith  - why did you close this?

**Comment by lucasff** [comment]
I have the exact same issue

**Comment by robwalkerco** [comment]
I was encountering this issue, and the only thing that finally sorted it was by removing the automatically created links in 'Build Phases - Link Binary with Libraries' and re-adding the links manually myself. This triggered the 'Build Settings - Framework Search Paths' option to be created.

**Comment by kyle-ssg** [comment]
Just in case this helps someone, I was receiving this in AppCenter due to using an outdated version of Xcode, moving from 10.1 to 11 solved this for me.
