### ISSUE TITLE
Not getting the crash report

### ISSUE THREAD

**Issue by swaroopa94** [corymsmith/react-native-fabric#67]
HI,
I am using React Native this module to find the crash report.
I have installed this fabric module and followed the instructions given.
But i am not getting the crash report.
I have to add any code in my view or any button action?

React-Native version:  0.25.1
Please help me to solve this.

**Comment by corymsmith** [comment]
If you're in dev / debug mode then errors are not sent as they are caught and shown in the Red Box.

**Comment by swaroopa94** [comment]
I created the binary and dowloaded and my app got crashed even then also i didnot get my crash report.

**Comment by GeoffreyPlitt** [comment]
I turned off DEV mode and also stopped debugging JS remotely. I also cannot get real crashes, just brings up RED error screen

**Comment by GeoffreyPlitt** [comment]
Update: OK it turns out you can't just turn off DEV and debugging, you have to actually run in release mode, i.e. https://facebook.github.io/react-native/docs/signed-apk-android.html with a keystore and everything.

So I did that, and the app now crashes as I would expect from Crashlytics.crash(). Still not seeing any crash in my dashboard.

Do I need to do ```init()``` or something in JS land? Like this? https://github.com/mikelambert/react-native-fabric-crashlytics

**Comment by corymsmith** [comment]
No you shouldn't have to do anything else assuming it's all set up correctly.

**Comment by corymsmith** [comment]
@swaroopa94 Is this still an issue, going to close this one for now, if so we can always reopen.

**Comment by GeoffreyPlitt** [comment]
I resolved my issues, and I posted my working code here in case anyone else ever has similar problems. Thanks for the help everyone. https://github.com/GeoffreyPlitt/react_native_minimal/tree/react_native_fabric
